# Generated by Django 4.0.5 on 2022-07-27 17:06

from django.db import migrations

def atribuir_valor_padrao(apps, schema_editor):
    Curso = apps.get_model('cursos', 'Curso')
    for curso in Curso.objects.filter(imagem=''):
        curso.imagem= 'https://eucontador.com.br/wp-content/uploads/2019/10/Cursos-Online.png'
        curso.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_imagem_de_curso_obrigatoria'),
    ]

    operations = [
        migrations.RunPython(atribuir_valor_padrao)
    ]
